# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-10 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, unique=True, verbose_name='Название статьи')),
                ('min_value', models.IntegerField(verbose_name='Минимальный порог')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('plan_value', models.IntegerField(verbose_name='Плановое значение')),
                ('date', models.DateField(verbose_name='Период')),
                ('virtual_value', models.IntegerField(verbose_name='Плановый приход')),
            ],
        ),
        migrations.CreateModel(
            name='ControlManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('managers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashitem.CashItem')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerCashItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField(verbose_name='Начало периода')),
                ('date_end', models.DateField(verbose_name='Конец периода')),
                ('cash_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashitem.CashItem')),
            ],
        ),
    ]
