# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-13 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashitem', '0002_auto_20200313_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlmanager',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='managercashitems',
            name='cash_items',
        ),
        migrations.DeleteModel(
            name='ControlManager',
        ),
        migrations.DeleteModel(
            name='ManagerCashItems',
        ),
    ]
