# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-13 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashitem', '0003_auto_20200313_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('managers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashitem.CashItem')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerCashItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField(verbose_name='Начало периода')),
                ('date_end', models.DateField(verbose_name='Конец периода')),
                ('cash_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashitem.CashItem')),
            ],
        ),
    ]
